# Generated by Django 6.0.5 on 2026-05-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Tranzaksiya ID')),
                ('order_id', models.CharField(db_index=True, max_length=255, verbose_name='Buyurtma ID')),
                ('amount', models.BigIntegerField(verbose_name='Summa (tiyin)')),
                ('state', models.IntegerField(choices=[(1, 'Yaratilgan'), (2, 'Bajarilgan'), (-1, 'Bekor qilingan'), (-2, 'Bekor qilingan (bajarilgandan keyin)')], default=1, verbose_name='Holat')),
                ('time', models.BigIntegerField(verbose_name='Payme vaqti (milliseconds)')),
                ('create_time', models.BigIntegerField(verbose_name='Yaratilgan vaqt (milliseconds)')),
                ('perform_time', models.BigIntegerField(default=0, verbose_name='Bajarilgan vaqt (milliseconds)')),
                ('cancel_time', models.BigIntegerField(default=0, verbose_name='Bekor qilingan vaqt (milliseconds)')),
                ('reason', models.IntegerField(blank=True, null=True, verbose_name='Bekor qilish sababi')),
                ('account', models.JSONField(default=dict, verbose_name="Account ma'lumotlari")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Payme Tranzaksiya',
                'verbose_name_plural': 'Payme Tranzaksiyalar',
                'db_table': 'payme_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='payme_trans_transac_163319_idx'), models.Index(fields=['order_id'], name='payme_trans_order_i_433bb7_idx'), models.Index(fields=['state'], name='payme_trans_state_1a024d_idx'), models.Index(fields=['create_time'], name='payme_trans_create__901ca4_idx')],
            },
        ),
    ]
