# Generated by Django 6.0.5 on 2026-05-06 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Buyurtma ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Mijoz ismi')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('items', models.JSONField(default=list, verbose_name='Mahsulotlar')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Jami summa (so'm)")),
                ('total_amount_tiyin', models.BigIntegerField(verbose_name='Jami summa (tiyin)')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('processing', 'Jarayonda'), ('shipped', 'Yuborilgan'), ('delivered', 'Yetkazilgan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holat')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name="To'lov usuli")),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Yetkazib berish manzili')),
                ('delivery_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shahar')),
                ('delivery_region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Viloyat')),
                ('customer_notes', models.TextField(blank=True, null=True, verbose_name='Mijoz izohi')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="To'langan vaqt")),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id'], name='orders_order_i_88e57b_idx'), models.Index(fields=['customer_phone'], name='orders_custome_d85dfb_idx'), models.Index(fields=['status'], name='orders_status_762191_idx'), models.Index(fields=['created_at'], name='orders_created_77e2b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255, verbose_name='Mahsulot ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('product_type', models.CharField(max_length=50, verbose_name='Mahsulot turi')),
                ('quantity', models.IntegerField(default=1, verbose_name='Miqdor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narx')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jami')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='payments.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtma Mahsuloti',
                'verbose_name_plural': 'Buyurtma Mahsulotlari',
                'db_table': 'order_items',
            },
        ),
    ]
