# Generated by Django 6.0.5 on 2026-05-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mahsulot ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Jami'),
        ),
    ]
