# Generated by Django 6.0.5 on 2026-05-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_orderitem_product_id_alter_orderitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Jami summa (so'm)"),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount_tiyin',
            field=models.BigIntegerField(default=0, verbose_name='Jami summa (tiyin)'),
        ),
    ]
