# Generated by Django 6.0.5 on 2026-05-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name="To'langan"),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yetkazib berish manzili'),
        ),
    ]
