# Generated by Django 6.0.5 on 2026-05-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_order_is_paid_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymetransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payme Tranzaksiya (Custom)', 'verbose_name_plural': 'Payme Tranzaksiyalar (Custom)'},
        ),
        migrations.RenameIndex(
            model_name='paymetransaction',
            new_name='custom_paym_transac_c30ff4_idx',
            old_name='payme_trans_transac_163319_idx',
        ),
        migrations.RenameIndex(
            model_name='paymetransaction',
            new_name='custom_paym_order_i_ea4eb4_idx',
            old_name='payme_trans_order_i_433bb7_idx',
        ),
        migrations.RenameIndex(
            model_name='paymetransaction',
            new_name='custom_paym_state_bce883_idx',
            old_name='payme_trans_state_1a024d_idx',
        ),
        migrations.RenameIndex(
            model_name='paymetransaction',
            new_name='custom_paym_create__312fa7_idx',
            old_name='payme_trans_create__901ca4_idx',
        ),
        migrations.AlterModelTable(
            name='paymetransaction',
            table='custom_payme_transactions',
        ),
    ]
